env: flex
runtime: nodejs

env_variables:
  DISCOGS_CONSUMER_KEY: REPLACE_CONSUMER_KEY
  DISCOGS_CONSUMER_SECRET: REPLACE_CONSUMER_SECRET
  DISCOGS_APP_URL: REPLACE_APP_URL

handlers:
  - url: /.*
    secure: always
    script: auto