name: 'Lint, test and build main'

on:
  push:
    branches:
      - main

jobs:
  lint-and-test-and-build-job:
    name: Lint, test and build
    uses: ./.github/workflows/reusable-lint-and-test-and-build-job.yml
